### ISSUE TITLE
Hidalgo throws an error for a user-provided distance matrix

### ISSUE THREAD

**Issue by selwyni** [Fradenti/intRinsic#2]
https://github.com/Fradenti/intRinsic/blob/cf16d3a2041ce984dcf2912acbaf949beaca9c22/R/compute_mus.R#L161

The Hidalgo function will throw an error `object 'n' is not found`  when provided a distance matrix that isn't of class 'dist'

I believe it's from this line - `compute_mus`  will have `n0` set but not `n`

Repro
```
data(rent99, package = "gamlss.data")
rent_distmat <- cluster::daisy(rent99, metric = "gower")
hidalgo_res <- Hidalgo(dist_mat = rent_distmat)
```

**Comment by Fradenti** [comment]
Thank you for pointing out this issue.

I should have addressed all the problems in `compute_mus` when passing a customized distance matrix.
The function also had problems since the object `rent_distmat` is of class `dissimilarity` and not `dist`.
The new function should handle that scenario as well.

Please install the new version of the package from GitHub using `remotes::install_github()` and let me know if something is still off.
